language: node_js
node_js:
  - 12
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install -g yarn
  - yarn
script:
  - yarn lint
  - yarn test
after_script:
  - yarn coveralls
