language: node_js
node_js:
  - 12
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install -g yarn
  - yarn
script:
  - yarn lint
  - yarn test
after_script:
  - yarn coveralls
