name: 🎉　Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cirrus-actions/rebase@master
        env:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
